ALTER TABLE "public"."CLIENTES" ADD COLUMN "DESCONTO ACESSORIO CELULAR" text;
ALTER TABLE "public"."CLIENTES" ADD COLUMN "DESCONTO BRINQUEDO" text;
ALTER TABLE "public"."CLIENTES" ADD COLUMN "DESCONTO ACESSORIO" text;
ALTER TABLE "public"."CLIENTES" ADD COLUMN "DESCONTO OUTROS" text;
