ALTER TABLE "CLIENTES" ADD COLUMN "GRUPO" text;
ALTER TABLE "CLIENTES" ADD COLUMN "GRUPO ROTA" text;

UPDATE "CLIENTES" c
SET
  "GRUPO" = cc."GRUPO",
  "GRUPO ROTA" = cc."GRUPO ROTA"
FROM "CLIENTE COMPLETA" cc
WHERE c."CODIGO" = cc."CODIGO";
