ALTER TABLE "BANCO_DE_DADOS" ADD COLUMN IF NOT EXISTS "session_id" INTEGER REFERENCES "DATAS DE INVENTÁRIO"("ID INVENTÁRIO");

CREATE INDEX IF NOT EXISTS idx_banco_dados_session_id ON "BANCO_DE_DADOS"("session_id");
