-- Add funcionario_id to Inventory Movement Tables
ALTER TABLE "ESTOQUE GERAL CARRO PARA ESTOQUE" 
ADD COLUMN IF NOT EXISTS funcionario_id BIGINT REFERENCES "FUNCIONARIOS"(id);

ALTER TABLE "ESTOQUE GERAL ESTOQUE PARA CARRO" 
ADD COLUMN IF NOT EXISTS funcionario_id BIGINT REFERENCES "FUNCIONARIOS"(id);

-- Add contacts JSONB to Suppliers
ALTER TABLE "FORNECEDORES" 
ADD COLUMN IF NOT EXISTS contatos JSONB DEFAULT '[]'::jsonb;
