ALTER TABLE "ESTOQUE CARRO: CLIENTE PARA O CARRO"
ADD COLUMN IF NOT EXISTS "pedido" BIGINT,
ADD COLUMN IF NOT EXISTS "data_horario" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "funcionario" TEXT,
ADD COLUMN IF NOT EXISTS "codigo_produto" BIGINT,
ADD COLUMN IF NOT EXISTS "barcode" TEXT,
ADD COLUMN IF NOT EXISTS "produto" TEXT,
ADD COLUMN IF NOT EXISTS "preco" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "ENTRADAS_cliente_carro" INTEGER DEFAULT 0;

ALTER TABLE "ESTOQUE CARRO: CARRO PARA O CLIENTE"
ADD COLUMN IF NOT EXISTS "pedido" BIGINT,
ADD COLUMN IF NOT EXISTS "data_horario" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "funcionario" TEXT,
ADD COLUMN IF NOT EXISTS "codigo_produto" BIGINT,
ADD COLUMN IF NOT EXISTS "barcode" TEXT,
ADD COLUMN IF NOT EXISTS "produto" TEXT,
ADD COLUMN IF NOT EXISTS "preco" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "SAIDAS_carro_cliente" INTEGER DEFAULT 0;

ALTER TABLE "ESTOQUE CARRO: ESTOQUE PARA O CARRO"
ADD COLUMN IF NOT EXISTS "pedido" BIGINT,
ADD COLUMN IF NOT EXISTS "data_horario" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "funcionario" TEXT,
ADD COLUMN IF NOT EXISTS "codigo_produto" BIGINT,
ADD COLUMN IF NOT EXISTS "barcode" TEXT,
ADD COLUMN IF NOT EXISTS "produto" TEXT,
ADD COLUMN IF NOT EXISTS "preco" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "ENTRADAS_estoque_carro" INTEGER DEFAULT 0;

ALTER TABLE "ESTOQUE CARRO: CARRO PARA O ESTOQUE"
ADD COLUMN IF NOT EXISTS "pedido" BIGINT,
ADD COLUMN IF NOT EXISTS "data_horario" TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS "funcionario" TEXT,
ADD COLUMN IF NOT EXISTS "codigo_produto" BIGINT,
ADD COLUMN IF NOT EXISTS "barcode" TEXT,
ADD COLUMN IF NOT EXISTS "produto" TEXT,
ADD COLUMN IF NOT EXISTS "preco" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "SAIDAS_carro_estoque" INTEGER DEFAULT 0;

