-- Create table for general configurations
CREATE TABLE IF NOT EXISTS configuracoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chave TEXT NOT NULL UNIQUE,
  valor TEXT
);

-- Insert seed value for email report recipient
INSERT INTO configuracoes (chave, valor)
VALUES ('email_relatorio_rota', 'admin@example.com')
ON CONFLICT (chave) DO NOTHING;

-- Enable RLS
ALTER TABLE configuracoes ENABLE ROW LEVEL SECURITY;

-- Create policies for authenticated users
CREATE POLICY "Allow read access for authenticated users"
  ON configuracoes
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow insert/update access for authenticated users"
  ON configuracoes
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);
