CREATE TABLE IF NOT EXISTS public.brinde (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_codigo BIGINT,
    cliente_nome TEXT,
    data TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    produto_codigo BIGINT,
    produto_nome TEXT,
    quantidade NUMERIC,
    funcionario_id BIGINT REFERENCES public."FUNCIONARIOS"(id),
    funcionario_nome TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
