-- Create table for collection action installments
CREATE TABLE IF NOT EXISTS acoes_cobranca_vencimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acao_cobranca_id BIGINT REFERENCES acoes_cobranca(id) ON DELETE CASCADE,
    vencimento DATE NOT NULL,
    valor NUMERIC(10,2) NOT NULL,
    forma_pagamento TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Update/Create Stock Valuation Function to calculate stock value based on last order
CREATE OR REPLACE FUNCTION get_clients_last_stock_value()
RETURNS TABLE (client_id INT, stock_value NUMERIC)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  WITH LastOrders AS (
    SELECT DISTINCT ON ("CÓDIGO DO CLIENTE")
      "CÓDIGO DO CLIENTE" as cid,
      "NÚMERO DO PEDIDO" as oid
    FROM "BANCO_DE_DADOS"
    WHERE "NÚMERO DO PEDIDO" IS NOT NULL
    ORDER BY "CÓDIGO DO CLIENTE", "DATA DO ACERTO" DESC, "HORA DO ACERTO" DESC
  ),
  OrderItems AS (
    SELECT
      bd."CÓDIGO DO CLIENTE",
      bd."SALDO FINAL",
      -- Prefer current product price from PRODUTOS table, fallback to historical sold price
      COALESCE(p."PREÇO", bd."PREÇO VENDIDO") as raw_price
    FROM "BANCO_DE_DADOS" bd
    JOIN LastOrders lo ON bd."NÚMERO DO PEDIDO" = lo.oid
    LEFT JOIN "PRODUTOS" p ON bd."COD. PRODUTO" = p."CODIGO"
    WHERE bd."SALDO FINAL" > 0
  )
  SELECT
    "CÓDIGO DO CLIENTE" as client_id,
    SUM(
      "SALDO FINAL" * 
      CASE 
        WHEN raw_price IS NULL THEN 0
        WHEN raw_price = '' THEN 0
        -- Robust parsing for Brazilian currency format: 1.234,56 -> 1234.56
        -- Remove dots (thousands), replace comma with dot (decimal)
        ELSE REPLACE(REPLACE(raw_price, '.', ''), ',', '.')::NUMERIC 
      END
    ) as stock_value
  FROM OrderItems
  GROUP BY "CÓDIGO DO CLIENTE";
END;
$$;
