-- Create table for system logs and issue reports
CREATE TABLE IF NOT EXISTS public.system_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    user_id BIGINT REFERENCES public."FUNCIONARIOS"(id),
    type TEXT NOT NULL, -- e.g., 'issue_report', 'export_log'
    description TEXT NOT NULL,
    meta JSONB
);

-- Enable RLS (Allow authenticated to insert, admins to select)
ALTER TABLE public.system_logs ENABLE ROW LEVEL SECURITY;

-- Policy for inserting logs (all authenticated users)
CREATE POLICY "Enable insert for authenticated users" ON public.system_logs
    FOR INSERT
    WITH CHECK (true);

-- Policy for viewing logs (all authenticated users for now, typically admins)
CREATE POLICY "Enable read for authenticated users" ON public.system_logs
    FOR SELECT
    USING (true);
