CREATE TABLE IF NOT EXISTS "public"."PIX" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "recebimento_id" BIGINT NOT NULL REFERENCES "public"."RECEBIMENTOS"("id") ON DELETE CASCADE,
    "venda_id" BIGINT,
    "nome_no_pix" TEXT NOT NULL,
    "banco_pix" TEXT NOT NULL DEFAULT 'BS2',
    "data_pix_realizado" TIMESTAMP WITH TIME ZONE,
    "confirmado_por" TEXT,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    CONSTRAINT "PIX_recebimento_id_key" UNIQUE ("recebimento_id")
);

ALTER TABLE "public"."PIX" ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT FROM pg_policies 
        WHERE tablename = 'PIX' 
        AND policyname = 'Enable read access for authenticated users'
    ) THEN
        CREATE POLICY "Enable read access for authenticated users" ON "public"."PIX"
            FOR SELECT TO authenticated USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT FROM pg_policies 
        WHERE tablename = 'PIX' 
        AND policyname = 'Enable insert for authenticated users'
    ) THEN
        CREATE POLICY "Enable insert for authenticated users" ON "public"."PIX"
            FOR INSERT TO authenticated WITH CHECK (true);
    END IF;

    IF NOT EXISTS (
        SELECT FROM pg_policies 
        WHERE tablename = 'PIX' 
        AND policyname = 'Enable update for authenticated users'
    ) THEN
        CREATE POLICY "Enable update for authenticated users" ON "public"."PIX"
            FOR UPDATE TO authenticated USING (true);
    END IF;
END $$;
