CREATE TABLE IF NOT EXISTS public.inativar_clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT NOT NULL,
    funcionario_nome TEXT,
    cliente_codigo BIGINT NOT NULL,
    cliente_nome TEXT,
    valor_venda NUMERIC(10, 2) DEFAULT 0,
    saldo_a_pagar NUMERIC(10, 2) DEFAULT 0,
    valor_pago NUMERIC(10, 2) DEFAULT 0,
    debito NUMERIC(10, 2) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add index for performance
CREATE INDEX IF NOT EXISTS idx_inativar_clientes_cliente_codigo ON public.inativar_clientes(cliente_codigo);
CREATE INDEX IF NOT EXISTS idx_inativar_clientes_created_at ON public.inativar_clientes(created_at);

-- Add permission module
INSERT INTO public.permissoes (setor, modulo, acesso)
VALUES 
  ('Administrador', 'Inativar Clientes', true),
  ('Gerente', 'Inativar Clientes', true),
  ('Financeiro', 'Inativar Clientes', true)
ON CONFLICT (setor, modulo) DO NOTHING;
