CREATE TABLE IF NOT EXISTS "DESPESAS" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Data" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "Grupo de Despesas" TEXT NOT NULL,
    "Detalhamento" TEXT NOT NULL,
    "Valor" NUMERIC NOT NULL,
    "funcionario_id" BIGINT NOT NULL REFERENCES "FUNCIONARIOS"("id")
);

ALTER TABLE "DESPESAS" ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Enable read access for all users" ON "DESPESAS" FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON "DESPESAS" FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON "DESPESAS" FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON "DESPESAS" FOR DELETE USING (true);
