-- Update existing NULL or empty values to 'ATIVO'
UPDATE "CLIENTES" 
SET "TIPO DE CLIENTE" = 'ATIVO' 
WHERE "TIPO DE CLIENTE" IS NULL OR "TIPO DE CLIENTE" = '';

-- Alter column to set default value 'ATIVO'
ALTER TABLE "CLIENTES" 
ALTER COLUMN "TIPO DE CLIENTE" SET DEFAULT 'ATIVO';

-- Alter column to be NOT NULL
ALTER TABLE "CLIENTES" 
ALTER COLUMN "TIPO DE CLIENTE" SET NOT NULL;
