CREATE TABLE IF NOT EXISTS sessoes_inventario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo TEXT NOT NULL CHECK (tipo IN ('GERAL', 'FUNCIONARIO')),
  funcionario_id BIGINT REFERENCES public."FUNCIONARIOS"(id),
  data_inicio TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  data_fim TIMESTAMP WITH TIME ZONE,
  status TEXT NOT NULL CHECK (status IN ('ABERTO', 'FECHADO')) DEFAULT 'ABERTO',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sessoes_inventario_status ON sessoes_inventario(status);
