CREATE TABLE IF NOT EXISTS public.acoes_cobranca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id BIGINT,
    acao TEXT,
    data_acao TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    nova_data_combinada DATE,
    funcionario_nome TEXT,
    funcionario_id BIGINT,
    cliente_id BIGINT,
    cliente_nome TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

DO $$
BEGIN
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'AÇOES DE COBRANÇA') THEN
        INSERT INTO public.acoes_cobranca (
            pedido_id,
            acao,
            data_acao,
            nova_data_combinada,
            funcionario_nome,
            funcionario_id,
            cliente_id,
            cliente_nome
        )
        SELECT
            "NÚMERO DO PEDIDO",
            "AÇÃO DE COBRANÇA",
            -- Handle potential casting issues safely or assume compatibility
            "DATA AÇÃO COBRANÇA"::TIMESTAMP WITH TIME ZONE,
            "NOVA DATA COMBINADA PAGAMENTO"::DATE,
            "NOME FUNCIONÁRIO",
            "CÓDIGO FUNCIONÁRIO",
            "COD. CLIENTE",
            "CLIENTE"
        FROM "AÇOES DE COBRANÇA";
    END IF;
END $$;

-- Rename old table to backup to prevent usage but keep data
ALTER TABLE IF EXISTS "AÇOES DE COBRANÇA" RENAME TO "AÇOES DE COBRANÇA_BACKUP";

-- Enable RLS
ALTER TABLE public.acoes_cobranca ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for authenticated users" ON public.acoes_cobranca
    FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Enable insert access for authenticated users" ON public.acoes_cobranca
    FOR INSERT
    TO authenticated
    WITH CHECK (true);

CREATE POLICY "Enable update access for authenticated users" ON public.acoes_cobranca
    FOR UPDATE
    TO authenticated
    USING (true);
