CREATE TABLE IF NOT EXISTS "PIX" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recebimento_id" BIGINT NOT NULL REFERENCES "RECEBIMENTOS"("id") ON DELETE CASCADE,
  "nome_no_pix" TEXT NOT NULL,
  "banco_pix" TEXT NOT NULL,
  "data_realizada" TIMESTAMP WITH TIME ZONE NOT NULL,
  "confirmado_por" TEXT,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  CONSTRAINT "PIX_recebimento_id_key" UNIQUE ("recebimento_id")
);

ALTER TABLE "PIX" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for authenticated users" ON "PIX"
    FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Enable insert for authenticated users" ON "PIX"
    FOR INSERT
    TO authenticated
    WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users" ON "PIX"
    FOR UPDATE
    TO authenticated
    USING (true);
