ALTER TABLE "DESPESAS" ADD COLUMN IF NOT EXISTS "prestador_servico" TEXT;
ALTER TABLE "DESPESAS" ADD COLUMN IF NOT EXISTS "tipo_servico" TEXT;
ALTER TABLE "DESPESAS" ADD COLUMN IF NOT EXISTS "tipo_combustivel" TEXT DEFAULT 'alcool';

